# SQL Server 轉發
# Nginx 需要在主設定檔 (nginx.conf) 最外層有 stream { include /etc/nginx/stream.d/*.conf; } 的區塊
server {
    listen 1433;

    # 現有 Windows SQL Server (後續遷移到 lxc 時，請改為 10.1.0.104:1433)
    proxy_pass 10.1.0.200:1433;
    
    # proxy_connect_timeout 1s;
    # proxy_timeout 3s;
}
