server {
    listen 80;
    server_name 220.135.228.168;

    # 測試階段：LXC 下的 xampp 轉到 /test
    location /test/ {
        proxy_pass http://10.1.0.100:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 根目錄轉發至 Windows XAMPP
    location / {
        proxy_pass http://10.1.0.200:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
